name: pr

on:
    pull_request:
        branches: [main]

defaults:
    run:
        shell: bash

jobs:
    core:
        steps:
            - uses: ./.github/actions/setup
            - name: lint
              run: pnpm lint

            - name: test
              run: pnpm test

    compatibility:
        strategy:
            matrix:
                node: [lts/*]
                os: [ubuntu-latest, windows-latest, macOS-latest]
                include:
                    - os: ubuntu-latest
                      node: 14
                    - os: ubuntu-latest
                      node: 18

        runs-on: ${{ matrix.os }}

        steps:
            - uses: ./.github/actions/setup
              with:
                  node: ${{ matrix.node }}

            - name: test
              run: pnpm test
