name: pr

on:
    pull_request:
        branches: [main]

defaults:
    run:
        shell: bash

jobs:
    check:
        strategy:
            matrix:
                node: [lts/*]
                os: [ubuntu-latest, windows-latest, macOS-latest]
                include:
                    - os: ubuntu-latest
                      node: 14
                    - os: ubuntu-latest
                      node: 18

        runs-on: ${{ matrix.os }}

        steps:
            - name: Setup re-po
              uses: ./.github/workflows/setup
              with:
                  node: ${{ matrix.node }}

            - name: Run linter
              run: pnpm lint

            - name: Test packages
              run: pnpm test
