name: pr

on:
    pull_request:
        branches: [main]

defaults:
    run:
        shell: bash

jobs:
    core:
        runs-on: ubuntu-latest
        timeout-minutes: 20
        steps:
            - name: Checkout re-po
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup re-po
              uses: ./.github/actions/setup

            - id: lint
              run: pnpm lint

            - id: test
              run: pnpm test

            - id: bench
              run: echo "BENCH_RESULTS=$(pnpm bench)" >> $GITHUB_ENV

            - name: Report benches
              uses: thollander/actions-comment-pull-request@v1
              with:
                  message: |
                      :judge: Your updated bench results:
                      ${{ env.BENCH_RESULTS }}
                  comment_includes: "updated bench results"
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    compatibility:
        needs: core
        timeout-minutes: 20
        strategy:
            matrix:
                node: [lts/*]
                os: [windows-latest, macos-latest]
                include:
                    - os: ubuntu-latest
                      node: 14
                    - os: ubuntu-latest
                      node: 18

        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout re-po
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup re-po
              uses: ./.github/actions/setup
              with:
                  node: ${{ matrix.node }}

            - id: test
              run: pnpm test
