name: pr

on:
    pull_request:
        branches: [main]

defaults:
    run:
        shell: bash

jobs:
    core:
        runs-on: ubuntu-latest
        timeout-minutes: 20
        steps:
            - name: Checkout re-po
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup re-po
              uses: ./.github/actions/setup

            - name: Lint
              run: pnpm lint

            - name: Test
              run: pnpm test

            - name: Bench
              id: bench
              # Avoid truncating the output to one line
              run: |
                  results=$(pnpm bench)
                  results="${results//'%'/'%25'}"
                  results="${results//$'\n'/'%0A'}"
                  results="${results//$'\r'/'%0D'}"                 
                  echo "::set-output name=results::$results"

            - name: Report benches
              uses: thollander/actions-comment-pull-request@v1
              with:
                  message: |
                      :weight_lifting: Your updated bench results:
                      ${{ steps.bench.outputs.results }}
                  comment_includes: "updated bench results"
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    compatibility:
        needs: core
        timeout-minutes: 20
        strategy:
            matrix:
                node: [lts/*]
                os: [windows-latest, macos-latest]
                include:
                    - os: ubuntu-latest
                      node: 14
                    - os: ubuntu-latest
                      node: 18

        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout re-po
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup re-po
              uses: ./.github/actions/setup
              with:
                  node: ${{ matrix.node }}

            - name: Test
              run: pnpm test
