name: publish

on:
    push:
        branches: [main]

jobs:
    update-gh-pages:
        runs-on: ubuntu-latest
        timeout-minutes: 20
        steps:
            - name: Checkout re-po
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup re-po
              uses: ./.github/actions/setup

            - name: Build redo.dev
              run: pnpm build-pages

            - name: Publish redo.dev
              run: |
                  git worktree add redo.dev/dist gh-pages
                  cd redo.dev/dist
                  git add --all
                  git commit -m "chore: publish to https://redo.dev"
                  git push origin gh-pages

    create-release-pr:
        runs-on: ubuntu-latest
        timeout-minutes: 20
        steps:
            - name: Checkout re-po
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup re-po
              uses: ./.github/actions/setup

            - name: Setup .npmrc
              run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

            - name: Create and publish versions
              uses: changesets/action@v1
              with:
                  commit: "chore: update versions"
                  title: "chore: update versions"
                  version: pnpm ci:version
                  publish: pnpm ci:publish
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
